"""empty message

Revision ID: 663858bc0f61
Revises: be6bade2d0ef
Create Date: 2024-02-19 20:05:41.253551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663858bc0f61'
down_revision = 'be6bade2d0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('species_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('species_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
